FROM nginx:stable-alpine

ARG VITE_BACKEND_URL
ARG VITE_LOCALES
ARG VITE_CURRENCY

ENV VITE_BACKEND_URL $VITE_BACKEND_URL
ENV VITE_LOCALES $VITE_LOCALES
ENV VITE_CURRENCY $VITE_CURRENCY

COPY ./dist /usr/share/nginx/html

EXPOSE 80
EXPOSE 443

CMD ["nginx","-g","daemon off;"]